api/urls.py
from django.conf.urls import url, include
from rest_framework import routers

from . import views


router = routers.DefaultRouter()
router.register(r'markets', views.MarketViewSet)
router.register(r'coins', views.CoinViewSet)
router.register(r'tickers', views.TickerViewSet)
router.register(r'query-tests', views.QueryTestsViewSet)


urlpatterns = router.urls
#
# summary_urlpatterns = [
#     url(r'^ma/', views.moving_average, name='ma'),
# ]
#
# urlpatterns += [
#     url(r'^summary/', include(summary_urlpatterns, namespace='summary')),
# ]

coinsdashboard/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout

from api.urls import urlpatterns as api_urlpatterns
from dashboard.urls import urlpatterns as dashboard_urlpatterns

urlpatterns = [
    url(r'^', include(dashboard_urlpatterns, namespace='dashboards')),
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(api_urlpatterns, namespace='api')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^login/$', login, {'template_name': 'login.html'}, name="login"),
    url(r'^logout/$', logout, name="logout"),
]

dashboard/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^check/$', views.check_queries, name='check_queries'),
]

dashboard/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

dashboard/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import JsonResponse
from django.urls import reverse

from .tables import DashboardTable



def dashboard(request):
    context = dict(
        table_coins=DashboardTable(
            id='table_coins',
            url=reverse('api:coin-list', kwargs={'format': 'json'}),
            columns=['code', 'name']
        ),
        table_markets=DashboardTable(
            id='table_markets',
            url=reverse('api:market-list', kwargs={'format': 'json'}),
            columns=['code', 'coin', 'unit']
        ),
        table_tickers=DashboardTable(
            id='table_tickers',
            url=reverse('api:ticker-list', kwargs={'format': 'json'}),
            columns=['market', 'price', 'volumn', 'date', 'sequence']
        )
    )
    return render(request, 'index.html', context)


def check_queries(request):
    context = dict(
        table_check_queries=DashboardTable(
            id='table_check_queries',
            url=reverse('api:querytest-list', kwargs={'format': 'json'}),
            columns=['name', 'params', 'result', 'expect', 'created_at', 'passed']
        )
    )
    return render(request, 'check.html', context)

dashboard/templates/components/html/head.html
{% load staticfiles %}

<meta charset="UTF-8">
<title>{% block title %}Coins Dashboard{% endblock %}</title>
<!-- Bootstrap Core CSS -->
<link href="{% static 'dashboard/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<!-- MetisMenu CSS -->
<link href="{% static 'dashboard/vendor/metisMenu/metisMenu.min.css' %}" rel="stylesheet">

<!-- Custom CSS -->
<link href="{% static 'dashboard/dist/css/sb-admin-2.min.css' %}" rel="stylesheet">

<!-- Morris Charts CSS -->
<link href="{% static 'dashboard/vendor/morrisjs/morris.css' %}" rel="stylesheet">

<!-- Custom Fonts -->
<link href="{% static 'dashboard/fonts/fontawesome.css' %}" rel="stylesheet" type="text/css">

dashboard/templates/components/html/nav.html
{% load staticfiles %}

<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Coins Dashboard</a>
    </div>
    <!-- /.navbar-header -->

    <ul class="nav navbar-top-links navbar-right">
        {% if not user.is_anonymous %}
            <li>
                Hi {{user.username}}!
            </li>
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-bell fa-fw"></i> <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-alerts">
<!--                    <li>-->
<!--                        <a href="#">-->
<!--                            <div>-->
<!--                                <i class="fa fa-comment fa-fw"></i> New Comment-->
<!--                                <span class="pull-right text-muted small">4 minutes ago</span>-->
<!--                            </div>-->
<!--                        </a>-->
<!--                    </li>-->
<!--                    <li class="divider"></li>-->
<!--                    <li>-->
<!--                        <a href="#">-->
<!--                            <div>-->
<!--                                <i class="fa fa-twitter fa-fw"></i> 3 New Followers-->
<!--                                <span class="pull-right text-muted small">12 minutes ago</span>-->
<!--                            </div>-->
<!--                        </a>-->
<!--                    </li>-->
<!--                    <li class="divider"></li>-->
<!--                    <li>-->
<!--                        <a href="#">-->
<!--                            <div>-->
<!--                                <i class="fa fa-envelope fa-fw"></i> Message Sent-->
<!--                                <span class="pull-right text-muted small">4 minutes ago</span>-->
<!--                            </div>-->
<!--                        </a>-->
<!--                    </li>-->
<!--                    <li class="divider"></li>-->
<!--                    <li>-->
<!--                        <a href="#">-->
<!--                            <div>-->
<!--                                <i class="fa fa-tasks fa-fw"></i> New Task-->
<!--                                <span class="pull-right text-muted small">4 minutes ago</span>-->
<!--                            </div>-->
<!--                        </a>-->
<!--                    </li>-->
<!--                    <li class="divider"></li>-->
<!--                    <li>-->
<!--                        <a href="#">-->
<!--                            <div>-->
<!--                                <i class="fa fa-upload fa-fw"></i> Server Rebooted-->
<!--                                <span class="pull-right text-muted small">4 minutes ago</span>-->
<!--                            </div>-->
<!--                        </a>-->
<!--                    </li>-->
<!--                    <li class="divider"></li>-->
                    <li>
                        <a class="text-center" href="#">
                            <strong>See All Alerts</strong>
                            <i class="fa fa-angle-right"></i>
                        </a>
                    </li>
                </ul>
<!--                 /.dropdown-alerts-->
            </li>
            <!-- /.dropdown -->
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a></li>
                    <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out fa-fw"></i> Logout</a></li>
                </ul>
                <!-- /.dropdown-user -->
            </li>
        {% endif %}
        <!-- /.dropdown -->
    </ul>
    <!-- /.navbar-top-links -->

    {% include "components/html/sidebar.html" %}
</nav>

dashboard/templates/components/html/script.html
{% load staticfiles %}

<!-- jQuery -->
<script src="{% static 'dashboard/vendor/jquery/jquery.min.js' %}"></script>

<!-- Bootstrap Core JavaScript -->
<script src="{% static 'dashboard/vendor/bootstrap/js/bootstrap.min.js' %}"></script>

<!-- Metis Menu Plugin JavaScript -->
<script src="{% static 'dashboard/vendor/metisMenu/metisMenu.min.js' %}"></script>

<!-- Morris Charts JavaScript -->
<script src="{% static 'dashboard/vendor/raphael/raphael.min.js' %}"></script>

<!--<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">-->
<!--<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>-->

dashboard/templates/components/html/sidebar.html
{% load staticfiles %}
<!--{-% load web_tags %}-->

<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <li>
                <a href="{% url 'dashboards:dashboard' %}"><i class="fas fa-tachometer-alt fa-fw"></i> Dashboard</a>
                <a href="{% url 'dashboards:check_queries' %}"><i class="fas fa-tachometer-alt fa-fw"></i> Check</a>
            </li>
        </ul>
    </div>
    <!-- /.sidebar-collapse -->
</div>
<!-- /.navbar-static-side -->

dashboard/templates/components/html/table.html
<table width="100%" class="table table-striped table-bordered table-hover"
       class="datatable" id="{{ id }}" source-url="{{ url }}" method="{{ method }}">
    <thead>
        <tr>
            {% for column in columns %}
                <th>{{ column }}</th>
            {% endfor %}
        </tr>
    </thead>
</table>